2d and 3d array 

In [135]:
import numpy as nn

In [136]:
# 2d array
arr=nn.array([
    [0,2,3,1,4,2]
             ])

In [137]:
nn.shape(arr)

(1, 6)

In [138]:
arr1=nn.array([
    [9,8,5,4,2],
    [9,6,4,2,8],
    [1,5,2,8,9],
    [5,8,4,5,2]
])

 nn.shape(arr1)

In [139]:
#1d
a=nn.array([8,3,5,2,5])

In [140]:
nn.shape(a)

(5,)

In [141]:
#3d array
arr3=nn.array([
    [[7,2,4,1,6],
    [9,6,5,4,2]],
    [[0,3,1,5,3],
    [8,4,5,2,1]],
    [[9,4,2,1,4],
    [8,4,2,1,5]]
])

In [142]:
nn.shape(arr3)

(3, 2, 5)

Subsetting/Slicing ndarray

In [143]:
arr1[0:4,0]

array([9, 9, 1, 5])

In [144]:
arr3[0,1,2]

np.int64(5)

In [145]:
arr3[0][1][3]=7

In [146]:
arr3

array([[[7, 2, 4, 1, 6],
        [9, 6, 5, 7, 2]],

       [[0, 3, 1, 5, 3],
        [8, 4, 5, 2, 1]],

       [[9, 4, 2, 1, 4],
        [8, 4, 2, 1, 5]]])

In [147]:
arr3[0]

array([[7, 2, 4, 1, 6],
       [9, 6, 5, 7, 2]])

In [148]:
arr3[0][0]

array([7, 2, 4, 1, 6])

In [149]:
arr.dtype

dtype('int64')

In [150]:
arr1.dtype

dtype('int64')

In [151]:
arr3.dtype

dtype('int64')

Type casting
means changing the data type of elements in numpy array

.astype() --> Creates the copy of an array, it means that it does not modify the original array

In [152]:
arr=arr.astype(float)

In [153]:
a.dtype

dtype('int64')

In [154]:
arr.dtype

dtype('float64')

In [155]:
arr.astype(nn.float32)

array([[0., 2., 3., 1., 4., 2.]], dtype=float32)

In [156]:
a=arr.astype(nn.float32)

In [157]:
a.dtype 

dtype('float32')

In [158]:
arr=arr.astype(nn.float32)

In [159]:
arr3=arr3.astype(nn.int32)

In [160]:
arr3.dtype

dtype('int32')

Built-in array Generation functions:



Creating array of zeros

In [161]:
mono=nn.zeros((7))

In [162]:
mono

array([0., 0., 0., 0., 0., 0., 0.])

In [163]:
print(mono)

[0. 0. 0. 0. 0. 0. 0.]


In [164]:
mono.dtype # by default it is float 64

dtype('float64')

In [165]:
mono=mono.astype(nn.int32)

In [166]:
n=nn.zeros((3,3),dtype=nn.int32)

In [167]:
n.dtype

dtype('int32')

In [168]:
mono.ndim

1

In [169]:
n.ndim

2

Creating array of ones

In [170]:
hh=nn.ones((3,4))

In [171]:
hh.dtype # it is also by default float 64

dtype('float64')

In [172]:
nnn=hh.astype(nn.int32)

In [173]:
hh.ndim

2

In [174]:
nnn.dtype

dtype('int32')

In [175]:
mmm=nn.ones((1,4,5))

In [176]:
mmm

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [177]:
mmm.ndim

3

In [178]:
bbb=mmm.astype(nn.int32)

In [179]:
bbb.dtype

dtype('int32')

In [180]:
bbb[0,2,3]

np.int32(1)

Creating identity matrix

In [181]:
bcbc=nn.eye(3,4)

In [182]:
bcbc

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [183]:
bcbc.dtype # by default it is also float64

dtype('float64')

In [184]:
zzzz=bcbc.astype(nn.int32)

In [185]:
zzzz

array([[1, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 1, 0]], dtype=int32)

zzzz.dtype

In [186]:
zzzz[1,1]

np.int32(1)

Creating array of constant values

In [187]:
zxzx=nn.full((3,3),"10") # we need to give the value # and what type of value we give it become that datatype

In [188]:
zxzx

array([['10', '10', '10'],
       ['10', '10', '10'],
       ['10', '10', '10']], dtype='<U2')

In [189]:
zxzx.dtype

dtype('<U2')

In [190]:
nnnnn=zxzx.astype(nn.int32)

In [191]:
nnnnn

array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]], dtype=int32)

Creating array of random values

In [192]:
random_array=nn.random.randint( 0,100, size=900)

In [193]:
random_array

array([ 0, 44,  8, 14, 96, 80, 54, 73, 57, 36, 48, 35,  2, 34, 89, 96, 60,
       76, 96, 88, 47, 23, 30, 69, 70,  1, 56, 36, 41, 99, 34, 69, 22, 41,
        5, 76, 33, 52, 20, 46, 27, 80, 79,  2, 57,  6,  2, 11, 45,  1, 34,
       98,  0, 58, 26, 32, 74, 98, 95, 52, 48, 17, 26, 73, 92, 73, 59, 59,
       26, 71, 57, 58, 60, 22, 71, 14, 32,  2, 50, 87, 77, 24, 84, 92, 82,
       69, 69, 24, 78, 77,  9,  8, 16, 63, 50,  3, 87, 58, 20,  5, 56, 56,
       88, 74, 81, 12, 80,  1, 55, 63, 27, 37, 57, 13, 25, 23, 36, 31, 42,
       29, 25, 81, 20, 23,  3, 54, 93, 97, 83, 95, 77, 10, 38, 52,  6, 54,
       82, 60, 38, 69, 34, 44, 70, 30, 13, 99,  7,  7, 33,  5,  4, 50, 10,
       52, 16, 57, 44, 38, 56, 41, 31,  2, 51, 36, 83, 71, 96, 88, 34,  7,
       53, 13, 87, 34,  0, 32, 52, 51, 82,  4, 71, 73, 92, 92, 98, 84, 37,
       71, 41,  4, 28,  4, 69, 20, 29, 93, 10, 61, 11, 48, 61, 89, 59, 42,
       50, 43, 38, 55, 74, 88, 50, 69, 29, 44, 45, 87, 49, 68, 24, 35,  2,
       93, 45, 83, 92, 78

In [194]:
nnnnnnnnn=random_array.astype(nn.float32)

In [195]:
nnnnnnnnn

array([ 0., 44.,  8., 14., 96., 80., 54., 73., 57., 36., 48., 35.,  2.,
       34., 89., 96., 60., 76., 96., 88., 47., 23., 30., 69., 70.,  1.,
       56., 36., 41., 99., 34., 69., 22., 41.,  5., 76., 33., 52., 20.,
       46., 27., 80., 79.,  2., 57.,  6.,  2., 11., 45.,  1., 34., 98.,
        0., 58., 26., 32., 74., 98., 95., 52., 48., 17., 26., 73., 92.,
       73., 59., 59., 26., 71., 57., 58., 60., 22., 71., 14., 32.,  2.,
       50., 87., 77., 24., 84., 92., 82., 69., 69., 24., 78., 77.,  9.,
        8., 16., 63., 50.,  3., 87., 58., 20.,  5., 56., 56., 88., 74.,
       81., 12., 80.,  1., 55., 63., 27., 37., 57., 13., 25., 23., 36.,
       31., 42., 29., 25., 81., 20., 23.,  3., 54., 93., 97., 83., 95.,
       77., 10., 38., 52.,  6., 54., 82., 60., 38., 69., 34., 44., 70.,
       30., 13., 99.,  7.,  7., 33.,  5.,  4., 50., 10., 52., 16., 57.,
       44., 38., 56., 41., 31.,  2., 51., 36., 83., 71., 96., 88., 34.,
        7., 53., 13., 87., 34.,  0., 32., 52., 51., 82.,  4., 71

Broadcasting (Explained)
Broadcasting is the ability of Numpy to perform arithmetic operations on arrays of different shapes - by automatically expanding the smaller array so that it matches the shape of the larger one

General broadcasting rules When operating on two arrays, NumPy compares their shapes element-wise. It starts with the trailing (i.e. rightmost) dimension and works its way left. Two dimensions are compatible when

they are equal, or

one of them is 1.

If these conditions are not met, a ValueError: operands could not be broadcast together exception is thrown, indicating that the arrays have incompatible shapes.

Input arrays do not need to have the same number of dimensions. The resulting array will have the same number of dimensions as the input array with the greatest number of dimensions, where the size of each dimension is the largest size of the corresponding dimension among the input arrays. Note that missing dimensions are assumed to have size one.

In [196]:
#Example 1: Scalar broadcasting
aa=nn.array([5,6,7,3,2])
a=nn.array([5])
nn.shape(aa)


(5,)

In [197]:
aaa=aa+a # because broadcasting has two rules if same or any is one aa(1,5) a(1,1)

In [198]:
print(aaa)

[10 11 12  8  7]


In [199]:
array1=nn.array([
    [5,4,2,1,5],
    [9,5,2,1,6]
])
array2=nn.array([8,3,4,1,3])


In [200]:
nn.shape(array1)

(2, 5)

In [201]:
nn.shape(array2)

(5,)

In [202]:
arrayy=array1+array2 

In [203]:
print(arrayy)

[[13  7  6  2  8]
 [17  8  6  2  9]]


In [204]:
arre=nn.array([
    [9,4,2,1,4,5],
    [5,3,2,7,2,6]
])
arre1=nn.array([
    [9],
    [6]
])

In [205]:
arrrr=arre+arre1

In [206]:
print(arrrr)

[[18 13 11 10 13 14]
 [11  9  8 13  8 12]]


In [207]:
arre1

array([[9],
       [6]])

In [208]:
arre

array([[9, 4, 2, 1, 4, 5],
       [5, 3, 2, 7, 2, 6]])

In [209]:
arr1 = nn.array([
    [1,2,3,4,5],
    [11,22,33,44,55]
])    # (2,5)
arr2 = nn.array([2,3,4,5])  # (1,4)

In [210]:
n=arr1+ # it is error because the broadcastig rule is same or one it is not same number 5 and 4 and not one

ValueError: operands could not be broadcast together with shapes (2,5) (4,) 

In [ ]:
 #Row broadcasting
arr1 = nn.array([
    [1,2,3,4,5],
    [11,22,33,44,55]
])
arr2 = nn.array([
    [2,3,4,5],
    [1,2,3,4]
])

new_arr = arr1 + arr2

print(new_arr)

In [ ]:
a = nn.array([
    [1],
    [2],
    [3] # (3,1)
])


In [ ]:
b=nn.array([1,2,3]) #(1,3)

In [ ]:
ab=a%b

In [ ]:
print(ab)