In [1]:
import numpy as np

In [2]:
array=np.array([9,8,6,0])

In [3]:
array.ndim

1

In [4]:
array1=np.array([
    [2,9,6,0,5],
    [6,3,0,8,2]
])

In [5]:
array1.ndim

2

In [6]:
array2=np.array([
    [[8,9,0,6,5],
     [4,0,7,2,8]],
    [[7,3,88,4,9],
     [5,0,4,6,9]]
])

In [7]:
array2.ndim

3

In [8]:
n=array2.reshape((5,4))

In [9]:
n

array([[ 8,  9,  0,  6],
       [ 5,  4,  0,  7],
       [ 2,  8,  7,  3],
       [88,  4,  9,  5],
       [ 0,  4,  6,  9]])

In [10]:
n.ndim

2

In [11]:
n[2,3]=98

In [12]:
n

array([[ 8,  9,  0,  6],
       [ 5,  4,  0,  7],
       [ 2,  8,  7, 98],
       [88,  4,  9,  5],
       [ 0,  4,  6,  9]])

In [13]:
array2

array([[[ 8,  9,  0,  6,  5],
        [ 4,  0,  7,  2,  8]],

       [[ 7, 98, 88,  4,  9],
        [ 5,  0,  4,  6,  9]]])

In [14]:
array1.shape

(2, 5)

In [15]:
array2.shape

(2, 2, 5)

In [16]:
array.shape

(4,)

In [17]:
array1.size

10

In [18]:
array.itemsize

8

In [19]:
mm=array2.astype(np.float32)

In [20]:
mm

array([[[ 8.,  9.,  0.,  6.,  5.],
        [ 4.,  0.,  7.,  2.,  8.]],

       [[ 7., 98., 88.,  4.,  9.],
        [ 5.,  0.,  4.,  6.,  9.]]], dtype=float32)

In [21]:
cvv=np.zeros((3,3),dtype=np.int32)

In [22]:
cvv

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]], dtype=int32)

In [23]:
cv=np.eye(7,9,dtype=np.int32)

In [24]:
cv

array([[1, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 1, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 1, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 1, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 1, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 1, 0, 0]], dtype=int32)

In [28]:
cv=np.identity(8)

In [29]:
cv

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])

In [30]:
cv=np.ones((3,3),dtype=np.int32)

In [31]:
cv

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int32)

In [32]:
cv=np.full((6,5),9)

In [33]:

    print(cv)

[[9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]
 [9 9 9 9 9]]


In [34]:
cv=np.random.randint(1,900,size=1000)

In [35]:
cv

array([ 33, 770, 331, 466, 317, 572,  84, 615, 226, 262, 511, 743, 792,
       807,  91, 187, 792,   5, 131,  22, 482, 654,   4, 213, 321, 101,
       540, 513, 470, 267, 410, 755,  78, 767, 391, 891, 706, 219, 663,
       652,  48, 595,  50, 440,  77, 295, 312, 375, 617, 372, 671, 307,
       537,  32, 198, 371, 204, 358, 498, 865, 448, 367, 218, 846, 834,
        42, 426, 758,   5, 250, 385, 743, 487, 352, 698, 833, 411, 115,
       888, 129, 229, 899, 142, 173, 579, 338, 510, 668,  32,  25, 595,
       856, 517, 872, 154, 825, 263, 245, 216, 143, 285, 840, 409,  48,
       267,  80, 839, 861, 382, 336, 771, 441, 735, 671, 347, 399, 296,
       508, 396,  78, 826, 480, 829, 791,   1, 153, 823, 245, 409, 793,
       419,  40, 482, 254, 492, 168, 258, 420, 613, 536,  74, 797, 713,
       357, 601, 346, 550, 572, 280, 412, 490, 415, 216, 203, 138, 833,
       714, 595, 838,  89, 427, 360, 244, 750, 648, 614,  73, 419, 744,
       632, 605, 459, 408, 668, 497, 831, 215,  45, 195, 702, 38

In [36]:
cv.ndim

1

In [37]:
#FLattern  it makes copy not view
n=array1.flatten()

In [38]:
array1

array([[2, 9, 6, 0, 5],
       [6, 3, 0, 8, 2]])

In [39]:
n

array([2, 9, 6, 0, 5, 6, 3, 0, 8, 2])

In [40]:
n[3]=99

In [41]:
n

array([ 2,  9,  6, 99,  5,  6,  3,  0,  8,  2])

In [42]:
array1

array([[2, 9, 6, 0, 5],
       [6, 3, 0, 8, 2]])

In [43]:
# ravel it makes view change in view is equal to change in orginial

n=array1.ravel()

In [44]:
n

array([2, 9, 6, 0, 5, 6, 3, 0, 8, 2])

In [45]:
n[3]=99

In [46]:
n

array([ 2,  9,  6, 99,  5,  6,  3,  0,  8,  2])

In [47]:
array1

array([[ 2,  9,  6, 99,  5],
       [ 6,  3,  0,  8,  2]])

In [48]:
# Broadcasting in it one element row or column should be same and one or both one

In [49]:
array

array([9, 8, 6, 0])

In [ ]:
array.shape

In [ ]:
cv=array*array1 # array=(1,4)
                # array1(2,5) because array has 4 columns but array1 has 5 thats why it cannot follow broasdcast rule.

In [ ]:
array2

In [ ]:
cv=array1*array2

In [ ]:
cv

In [ ]:
cv=array1+array2

In [ ]:
cv

In [ ]:
cv=array1-array2

In [ ]:
cv

In [ ]:
cv=np.max(array1,axis=1)

In [ ]:
cv

In [ ]:
array1

In [ ]:
cv=np.min(array1,axis=1)# axis=0   is column wise axis=1c is row wise 

In [ ]:
cv

In [210]:
cv=np.argmax(array1,axis=0)

In [211]:
cv

array([1, 0, 0, 1, 0])

In [207]:
cv=np.argmin(array,axis=0)

In [ ]:
cv

In [203]:
cv

array([0, 1, 1, 0, 1])

In [197]:
print("hello")

hello
