In [1]:
import numpy as np

In [2]:
a=np.arange(10)

In [3]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
av=np.array([
    [3],
    [5]
])

In [5]:
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [6]:
a.shape

(10,)

In [7]:
b=np.array([
    [9,4,2,1,5,3],
    [7,4,2,1,5,6],
    [9,42,5,6,4,6]
])

In [8]:
b.shape

(3, 6)

In [9]:
n=a+b # (2,6)
      # (3,6)

ValueError: operands could not be broadcast together with shapes (10,) (3,6) 

In [10]:
n=b*5

In [11]:
n

array([[ 45,  20,  10,   5,  25,  15],
       [ 35,  20,  10,   5,  25,  30],
       [ 45, 210,  25,  30,  20,  30]])

In [12]:
n=a+6

In [13]:
n

array([ 6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [14]:
a=np.array([
    [[2,4,2,5,6],
     [9,6,3,2,1]],
    [[3,1,35,5,5],
    [0,4,2,4,2]]
])

In [15]:
a.shape

(2, 2, 5)

In [16]:
n=a*av   #(2,1) av([
                #[[3,3,3,3,3],
                 #[5,5,5,5,5]],
                #[[3,3,3,3,3],
                #[5,5,5,5,5]]
        #(2,2,5) a([
#    [[2,4,2,5,6],
 #    [9,6,3,2,1]],
 #   [[3,1,35,5,5],
 #   [0,4,2,4,2]]
#])

In [17]:
n

array([[[  6,  12,   6,  15,  18],
        [ 45,  30,  15,  10,   5]],

       [[  9,   3, 105,  15,  15],
        [  0,  20,  10,  20,  10]]])

In [18]:
n=a*b # unable of broadcabst because it is not follow broadcast rule (same or one)

ValueError: operands could not be broadcast together with shapes (2,2,5) (3,6) 

Reshape
changes the shape (dimensions) of numpy array without changing it data

In [ ]:
arr=np.array([[1,3,5,7,5],[5,2,6,2,6]])

In [19]:
arr.shape

NameError: name 'arr' is not defined

In [ ]:
n=arr.reshape(2,1,5) # in reshappe we can convert in any type of ndim

In [ ]:
n

In [20]:
n=arr.reshape(10) # it make view not copy if change in view lead to change in copy if we can give -1 as argument numpy authomaticalkly make#  the row and column but we use only one

NameError: name 'arr' is not defined

In [ ]:
n

In [ ]:
n[0,2]=89

In [21]:
n

array([[[  6,  12,   6,  15,  18],
        [ 45,  30,  15,  10,   5]],

       [[  9,   3, 105,  15,  15],
        [  0,  20,  10,  20,  10]]])

In [22]:
arr

NameError: name 'arr' is not defined

In [ ]:
n.ndim

Flatten and Ravel
Flatten --> returns the copy of array collapsed into 1D. Changes to the flatten array not affect the original array

Ravel --> Returns the view of array in collapsed 1D. Changes to raveled array affect the original array

In [23]:
a

array([[[ 2,  4,  2,  5,  6],
        [ 9,  6,  3,  2,  1]],

       [[ 3,  1, 35,  5,  5],
        [ 0,  4,  2,  4,  2]]])

In [24]:
bn=a.flatten() # it only make one dimnesion only and make copy not view

In [25]:
bn

array([ 2,  4,  2,  5,  6,  9,  6,  3,  2,  1,  3,  1, 35,  5,  5,  0,  4,
        2,  4,  2])

In [26]:
bn[3]=98

In [27]:
bn

array([ 2,  4,  2, 98,  6,  9,  6,  3,  2,  1,  3,  1, 35,  5,  5,  0,  4,
        2,  4,  2])

In [28]:
a

array([[[ 2,  4,  2,  5,  6],
        [ 9,  6,  3,  2,  1]],

       [[ 3,  1, 35,  5,  5],
        [ 0,  4,  2,  4,  2]]])

In [29]:
bn=a.ravel() # it also make one dimension but it make view not copy. Change in view =change in original

In [30]:
bn

array([ 2,  4,  2,  5,  6,  9,  6,  3,  2,  1,  3,  1, 35,  5,  5,  0,  4,
        2,  4,  2])

In [31]:
bn[7]=999

In [32]:
n


array([[[  6,  12,   6,  15,  18],
        [ 45,  30,  15,  10,   5]],

       [[  9,   3, 105,  15,  15],
        [  0,  20,  10,  20,  10]]])

In [33]:
array1=np.array([
    
    [[8,5,3,2,1]],
    [[7,5,9,4,2]],

    [[9,6,8,5,3]],
    [[6,4,0,8,3]]
])

In [34]:
array1.ndim

3

In [35]:
array1.shape

(4, 1, 5)

In [36]:
a.shape

(2, 2, 5)

In [37]:
b=np.array([3])

In [ ]:
c=a+