In [2]:
import numpy as np

In [3]:
array1=np.array([
    [2,4,6,6,8,7],
    [5,0,7,3,9,6],
    [7,0,7,5,3,2]
])

In [4]:
array2=np.array([
    [7,5,99,7,0],
    [6,2,1,5,2]
])

In [5]:
array3=np.array([
    [8,9,2,1,4,3]
])

In [6]:
array1.max()

np.int64(9)

In [7]:
array1.min()

np.int64(0)

In [8]:
array2.max()

np.int64(99)

In [9]:
array2.min()

np.int64(0)

In [10]:
array3.max()

np.int64(9)

In [11]:
array2.min()

np.int64(0)

**FILTERING**

In [12]:
max=5
print(array1>max) # it gives in the form of true false
array1[array1>max]# it give in the form of numbers
array1[array1>max]=max

[[False False  True  True  True  True]
 [False False  True False  True  True]
 [ True False  True False False False]]


In [13]:
array1

array([[2, 4, 5, 5, 5, 5],
       [5, 0, 5, 3, 5, 5],
       [5, 0, 5, 5, 3, 2]])

In [14]:
ab=np.array([4,8,99,2,1,0])

In [15]:
ab[ab>max]

array([ 8, 99])

In [16]:
ab[ab>max]=max

In [17]:
ab

array([4, 5, 5, 2, 1, 0])

**Stacking
Joins a sequence of an arrays along new axis** it is method of joinig method arrray along horizontal axis or vertical axis

In [ ]:
a=np.array([
    [1,2,3,2,4,5],
    [9,7,99,5,2,1]
])

In [ ]:
b=np.array([[8,4,2,1,5],
           [9,7,5,8,9]])

In [ ]:
bn

array([[ 1,  2,  3,  2,  4,  5,  8,  4,  2,  1,  5],
       [ 9,  7, 99,  5,  2,  1,  9,  7,  5,  8,  9]])

In [ ]:
nn=np.array([
    [[9,3,2,5],
     [9,4,2,5]],
    [[8,5,3,6],
     [9,8,0,6]]
])

In [ ]:
a=np.array([1,2,3,4,5])
b=np.array([
    [1,2,4,5,5],
    [5,3,1,4,3]
])

In [ ]:
abb=np.vstack((a,b))

In [ ]:
abb

array([[1, 2, 3, 4, 5],
       [1, 2, 4, 5, 5],
       [5, 3, 1, 4, 3]])

In [ ]:
aaa=np.array([1,2,4])
bbb=np.array([[2,5,3,45,2,5]])

In [ ]:
aabbb=np.hstack((a,b))

In [ ]:
aaa=aaa.reshape(1,-1)

In [ ]:
aabbb

array([[ 1,  2,  3,  2,  4,  5,  8,  4,  2,  1,  5],
       [ 9,  7, 99,  5,  2,  1,  9,  7,  5,  8,  9]])