In [ ]:
import numpy as np

In [6]:
%%time

list1=[i for i in range(100000)] # we are seeing how much time it should take how much numpy take we compare
list2=[i for i in range(100000)]

CPU times: total: 46.9 ms
Wall time: 45.6 ms


In [17]:
%%time
a=np.arange(5) # very faster than python  numpy is also 19 times fater
a1=np.arange(5)

CPU times: total: 0 ns
Wall time: 1.24 ms


In [15]:
%%time
print(a)

[    0     1     2 ... 99997 99998 99999]
CPU times: total: 0 ns
Wall time: 1.62 ms


In [16]:
%%time
l=list1*list2

TypeError: can't multiply sequence by non-int of type 'list'

In [19]:
%%time
m=a*a1

CPU times: total: 0 ns
Wall time: 159 μs


In [20]:
print(m)

[ 0  1  4  9 16]


In [22]:
np.shape(a)

(5,)

In [23]:
print(len(a))

5


In [24]:
np.size(a)

5

In [46]:
n=np.array([1,7,8,6,9],dtype=np.int32)

In [47]:
b=np.size(n)

In [28]:
v=np.shape(n)

In [29]:
print(b)
print(v)

5
(5,)


In [48]:
print(type(n))

<class 'numpy.ndarray'>


In [49]:
print(n.dtype)

int32


In [53]:
g=np.array(["a","b","c","v","cc"])

NameError: name '_string' is not defined

In [57]:
s=np.array([0.87,0.65,0.23,0.87,1.98],dtype=np.float32) # changing data type float 64 to 32

In [55]:
print(s)

[0.87 0.65 0.23 0.87 1.98]


In [56]:
print(s.dtype)

float32


In [63]:
# also access like list index
print(n[0])
print(n[2])
print(n[-1])

77
8
9


In [65]:
# also access like list index
print(g[0])
print(g[2])
print(g[-1])
print(g)

a
c
cc
['a' 'b' 'c' 'v' 'cc']


In [66]:
# also access like list index
print(s[0])
print(s[2])
print(s[-1])
print(s)

0.87
0.23
1.98
[0.87 0.65 0.23 0.87 1.98]


In [64]:
# also slicing or change or overwrite element
n[0]=77
print(n)

[77  7  8  6  9]


In [67]:
s[0]=9
print(s)

[9.   0.65 0.23 0.87 1.98]


In [68]:
g[0]=99
g[2]=8
g[4]="gg"
print(g)

['99' 'b' '8' 'v' 'gg']


In [69]:
# one dimensional array
onedarray=np.array([1,2,4,5,6])

In [70]:
onedarray.dtype

dtype('int64')

In [75]:
print(onedarray[4])

6


In [76]:
print(np.size(onedarray))
print(np.shape(onedarray))

5
(5,)


In [78]:
onedarray[0]=99
print(onedarray)

[99  2  4  5  6]


In [145]:
# two dimensional array
tn=np.array([[1,4,56,6,8],
            [4,2,6,7,"4"]],dtype=np.int64)

In [146]:
print(tn)

[[ 1  4 56  6  8]
 [ 4  2  6  7  4]]


In [147]:
print(type(tn))

<class 'numpy.ndarray'>


In [148]:
print(tn.dtype)

int64


In [149]:
print(np.size(tn))

10


In [150]:
print(np.shape(tn))

(2, 5)


In [151]:
# Zero row and column 
print(tn[0][0])
print(tn[0,4])
print(tn[0,1])
print(tn[0,2])
print(tn[0,3])

1
8
4
56
6


In [152]:
print(tn[1][4])

4


In [153]:
print(tn[1,0])

4


In [154]:
print(tn[1,3])

7


In [155]:
print(tn[1,2])

6


In [156]:
print(tn[1,-3])

6


In [157]:
tn[0][0]=99

In [158]:
print(tn)

[[99  4 56  6  8]
 [ 4  2  6  7  4]]


In [159]:
tn[0,3]=64

In [160]:
tn[1,0]="768"
print(tn)

[[ 99   4  56  64   8]
 [768   2   6   7   4]]
