Part 4: Vectorization
1. Create two arrays A and B of 5 random integers each. Perform element-wise addition, subtraction,
multiplication, and division without using loops.
2. Using vectorization, compute the square root, exponential, and sine of all elements in a single array.
[Hint: for computing using np.sqrt(), For computing use np.exp(), For Computing sine using np.sin()]
3. Given a list of 10 temperatures in Celsius, convert them to Fahrenheit using a single vectorized
expression.
[Hint: for Celsius to Fahrenheit conversion use formula  °F = (°C × 9/5) + 32]

In [3]:
import numpy as np 


In [4]:
A=np.random.randint(1,100,size=5)

In [5]:
A

array([43, 57, 33, 22, 80], dtype=int32)

In [20]:
B=np.random.randint(1,70,size=5)

In [21]:
B

array([48, 18, 60, 25, 16], dtype=int32)

In [22]:
A.shape

(5,)

In [30]:
np.shape(B)

(5,)

In [31]:
AB=A+B

In [32]:
AC=A-B

In [33]:
AD=A*B

In [34]:
AE=A/B

In [35]:
AB

array([91, 75, 93, 47, 96], dtype=int32)

In [36]:
AC

array([ -5,  39, -27,  -3,  64], dtype=int32)

In [37]:
AD

array([2064, 1026, 1980,  550, 1280], dtype=int32)

In [49]:
AE

array([0.89583333, 3.16666667, 0.55      , 0.88      , 5.        ])

In [47]:
sqrt=np.sqrt((A,B))

In [48]:
sqrt

array([[6.55743852, 7.54983444, 5.74456265, 4.69041576, 8.94427191],
       [6.92820323, 4.24264069, 7.74596669, 5.        , 4.        ]])

In [44]:
sqrt1=np.sqrt(B)

In [45]:
sqrt1

array([6.92820323, 4.24264069, 7.74596669, 5.        , 4.        ])

In [51]:
exp=np.exp((A,B))

In [52]:
exp

array([[4.72783947e+18, 5.68572000e+24, 2.14643580e+14, 3.58491285e+09,
        5.54062238e+34],
       [7.01673591e+20, 6.56599691e+07, 1.14200739e+26, 7.20048993e+10,
        8.88611052e+06]])

In [53]:
sin=np.sin((A,B))

In [54]:
sin

array([[-0.83177474,  0.43616476,  0.99991186, -0.00885131, -0.99388865],
       [-0.76825466, -0.75098725, -0.30481062, -0.13235175, -0.28790332]])

In [57]:
C=np.array([35,23,33,45,29,40,39,42,55,19])

In [73]:
F=(C*9/5)+32

In [74]:
F

array([ 95. ,  73.4,  91.4, 113. ,  84.2, 104. , 102.2, 107.6, 131. ,
        66.2])