Part 4: Broadcasting
1. Create a 3×3 matrix – named as A and:
 - Add 10 to it (scalar broadcasting).
 - Add a row vector [1, 2, 3] to it (row broadcasting).
 - Add a column vector [[1], [2], [3]] to it (column broadcasting).
2. Predict the shape of each result before executing the code. 

In [6]:
import numpy as np

In [23]:
A=np.array([

      [1,4,3],
      [2,3,4],
      [4,5,6]


    
])

In [24]:
 A

array([[1, 4, 3],
       [2, 3, 4],
       [4, 5, 6]])

In [30]:
 A.shape

(3, 3)

In [32]:
np.shape(10)

()

In [33]:
A=A+10

In [34]:
A

array([[21, 24, 23],
       [22, 23, 24],
       [24, 25, 26]])

In [39]:
B.shape

(3,)

In [35]:
B=np.array([1,2,3])

In [36]:
A+B

array([[22, 26, 26],
       [23, 25, 27],
       [25, 27, 29]])

In [37]:
c=np.array([
[1],
[2],
[3] 
    
])

In [40]:
A.shape

(3, 3)

In [41]:
c.shape

(3, 1)

In [42]:
A+c

array([[22, 25, 24],
       [24, 25, 26],
       [27, 28, 29]])