Part 4: Reshape, Flatten, Ravel
1. Create an array of numbers from 1–12. Reshape it into a (3×4) array. Then reshape it again into (2×6).
2. Use .flatten() and .ravel() on a 2D array and show the difference between them when you modify the
flattened and raveled array.
3. Given an array:
arr = np.arange(1, 10).reshape(3, 3)
 - Convert it into a 1D array using both methods.
 - Show if changes in one reflect in the original array. 

In [3]:
import numpy as np

In [4]:
array=np.array([1,2,3,4,5,6,7,8,9,10,11,12])

In [9]:
array=array.reshape(3,4)

In [10]:
array

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [14]:
array=array.reshape(2,6)

In [15]:
array

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [16]:
array1=np.array([
    [2,6,8,1,5],
    [9,6,0,4,2],
    [7,9,5,8,2]])

In [17]:
array1

array([[2, 6, 8, 1, 5],
       [9, 6, 0, 4, 2],
       [7, 9, 5, 8, 2]])

In [24]:
# Flatten
v=array1.flatten()

In [25]:
v

array([2, 6, 8, 1, 5, 9, 6, 0, 4, 2, 7, 9, 5, 8, 2])

In [26]:
# ravel
r=array1.ravel()

In [27]:
r

array([2, 6, 8, 1, 5, 9, 6, 0, 4, 2, 7, 9, 5, 8, 2])

FLATTEN makes thE copy of ARRAY which is used when if we do not need to change the original array we use flatten.
RAVEL makes the View of ARRAY which means change in view equal to change in orginal array. 

In [28]:
v[1]

np.int64(6)

In [29]:
v[1]=78

In [30]:
v

array([ 2, 78,  8,  1,  5,  9,  6,  0,  4,  2,  7,  9,  5,  8,  2])

In [31]:
v[1]

np.int64(78)

In [32]:
array1

array([[2, 6, 8, 1, 5],
       [9, 6, 0, 4, 2],
       [7, 9, 5, 8, 2]])

In [33]:
r[1]

np.int64(6)

In [35]:
r[4]=100

In [36]:
r

array([  2,  32,   8,   1, 100,   9,   6,   0,   4,   2,   7,   9,   5,
         8,   2])

In [37]:
array1

array([[  2,  32,   8,   1, 100],
       [  9,   6,   0,   4,   2],
       [  7,   9,   5,   8,   2]])

In [38]:
array3=np.arange(1,10)

In [39]:
array3

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [42]:
nnn=array3.reshape(3,3)

In [43]:
nnn[1,1]=75

In [44]:
nnn

array([[ 1,  2,  3],
       [ 4, 75,  6],
       [ 7,  8,  9]])

In [45]:
array3

array([ 1,  2,  3,  4, 75,  6,  7,  8,  9])

In [46]:
nnn[1,0:3]=9

In [47]:
nnn


array([[1, 2, 3],
       [9, 9, 9],
       [7, 8, 9]])

In [59]:
array3

array([ 1,  2, 88,  9,  9,  9,  7,  8,  9])

In [60]:
mmm=array3.flatten()

In [61]:
mmm.ndim

1

In [62]:
mmm

array([ 1,  2, 88,  9,  9,  9,  7,  8,  9])

In [63]:
mmm[2]=88

In [64]:
mmm

array([ 1,  2, 88,  9,  9,  9,  7,  8,  9])

In [65]:
array3

array([ 1,  2, 88,  9,  9,  9,  7,  8,  9])

In [66]:
mmm[3]=110

In [67]:
mmm

array([  1,   2,  88, 110,   9,   9,   7,   8,   9])

In [68]:
array3

array([ 1,  2, 88,  9,  9,  9,  7,  8,  9])

In [71]:
bn=array3.ravel()

In [72]:
bn

array([ 1,  2, 88,  9,  9,  9,  7,  8,  9])

In [73]:
bn[6]=180

In [74]:
bn

array([  1,   2,  88,   9,   9,   9, 180,   8,   9])

In [75]:
array3

array([  1,   2,  88,   9,   9,   9, 180,   8,   9])